# Project: Project10
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = Untitled11.o Untitled12.o
LINKOBJ  = Untitled11.o Untitled12.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib32" -static -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 C:/Users/Suyog_Asus/Downloads/Compressed/glut/lib/OPENGL32.LIB -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32 C:/Users/Suyog_Asus/Downloads/Compressed/glut/lib/glut32.lib -m32 -g3
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Project10.exe
CXXFLAGS = $(CXXINCS) -m32 -g3 -DGLUT_STATIC
CFLAGS   = $(INCS) -m32 -g3
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Untitled11.o: Untitled11.cpp
	$(CPP) -c Untitled11.cpp -o Untitled11.o $(CXXFLAGS)

Untitled12.o: Untitled12.cpp
	$(CPP) -c Untitled12.cpp -o Untitled12.o $(CXXFLAGS)
